# Generated by Django 6.0.4 on 2026-07-16 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0007 employe est major'),
        ('patients', '0007_remove_patient_patient_nom_prenom_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deces', models.DateTimeField()),
                ('lieu_deces', models.CharField(choices=[('hopital', "À l'hôpital"), ('hors_hopital', "Hors de l'hôpital (transfert)")], default='hopital', max_length=15)),
                ('cause_presumee', models.TextField(blank=True, help_text="Cause présumée à l'entrée en morgue, avant autopsie éventuelle.")),
                ('necessite_autopsie', models.BooleanField(default=False, help_text='Mort suspecte / cadre judiciaire, ou demande scientifique/diagnostique.')),
                ('statut', models.CharField(choices=[('en_attente_autopsie', "En attente d'autopsie"), ('dispense_autopsie', 'Autopsie non requise'), ('autopsie_terminee', 'Autopsie terminée'), ('corps_remis', 'Corps remis à la famille')], default='dispense_autopsie', max_length=25)),
                ('reclamant_nom', models.CharField(blank=True, max_length=150)),
                ('reclamant_lien', models.CharField(blank=True, help_text='Ex : époux, fille, frère...', max_length=100)),
                ('reclamant_telephone', models.CharField(blank=True, max_length=30)),
                ('date_remise_corps', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin_constatant', models.ForeignKey(blank=True, help_text='Médecin ayant constaté le décès.', limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_constates', to='comptes.employe')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deces', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Décès',
                'verbose_name_plural': 'Décès',
                'ordering': ['-date_deces'],
            },
        ),
        migrations.CreateModel(
            name='Autopsie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('judiciaire', 'Judiciaire (réquisition)'), ('medicale', 'Médicale (scientifique / diagnostique)')], default='medicale', max_length=12)),
                ('date_autopsie', models.DateTimeField()),
                ('cause_deces_determinee', models.TextField(blank=True)),
                ('constatations', models.TextField(blank=True)),
                ('rapport_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin_legiste', models.ForeignKey(blank=True, limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopsies_realisees', to='comptes.employe')),
                ('deces', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autopsie', to='morgue.deces')),
            ],
            options={
                'verbose_name': 'Autopsie',
                'verbose_name_plural': 'Autopsies',
                'ordering': ['-date_autopsie'],
            },
        ),
    ]
