# Generated by hand to match Django 6.0.4 migration format

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0001_initial'),
        ('chirurgie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deces',
            name='operation_liee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deces_lies',
                to='chirurgie.operation',
                help_text=(
                    "À renseigner si le décès fait suite à une complication "
                    "chirurgicale péri-opératoire. Conditionne qui peut valider "
                    "le rapport d'autopsie (voir Capacite.AUTOPSIE_VALIDER_PERIOP) "
                    ": le Chef de Chirurgie si renseigné, n'importe quel médecin "
                    "sinon."
                ),
            ),
        ),
    ]