# Generated by Django 6.0.4 on 2026-07-19 00:38

import django.db.models.deletion
import morgue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009 chef chirurgie role'),
        ('morgue', '0002 deces operation liee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopsie',
            name='medecin_legiste',
            field=models.ForeignKey(blank=True, limit_choices_to=morgue.models._roles_actes_medicaux, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopsies_realisees', to='comptes.employe'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='medecin_constatant',
            field=models.ForeignKey(blank=True, help_text='Médecin ayant constaté le décès.', limit_choices_to=morgue.models._roles_actes_medicaux, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_constates', to='comptes.employe'),
        ),
    ]
