# Generated by Django 6.0 on 2026-07-23 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirurgie', '0003_remove_operation_chirurgien_principal_and_more'),
        ('morgue', '0003_alter_autopsie_medecin_legiste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deces',
            name='operation_liee',
            field=models.ForeignKey(blank=True, help_text="À renseigner si le décès fait suite à une complication chirurgicale péri-opératoire. Conditionne qui peut valider le rapport d'autopsie (voir Capacite.AUTOPSIE_VALIDER_PERIOP) : le Chef de Chirurgie si renseigné, n'importe quel médecin sinon.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_lies', to='chirurgie.interventionchirurgicale'),
        ),
    ]
