# Generated by Django 6.0.4 on 2026-07-16 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_add_indexes'),
        ('comptes', '0007 employe est major'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='demandeanalyse',
            name='analyse_patient_statut_idx',
        ),
        migrations.AlterField(
            model_name='demandeanalyse',
            name='demandeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_envoyees', to='comptes.employe', verbose_name='Médecin demandeur'),
        ),
    ]
