# Generated by Django 6.0.4 on 2026-07-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0007 employe est major'),
        ('consultations', '0006_remove_consultation_consult_patient_date_idx_and_more'),
        ('hospitalisations', '0001_initial'),
        ('patients', '0007_remove_patient_patient_nom_prenom_idx_and_more'),
        ('services', '0003 chef de service allow laborantin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles_bloc', to='services.service')),
            ],
            options={
                'verbose_name': 'Salle de bloc',
                'verbose_name_plural': 'Salles de bloc',
                'ordering': ['service', 'nom'],
                'unique_together': {('nom', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(help_text='Ex. « Cure de hernie inguinale »', max_length=200)),
                ('date_heure_prevue', models.DateTimeField()),
                ('duree_estimee_min', models.PositiveIntegerField(default=60)),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True)),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('complication', 'Terminée avec complication'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='planifiee', max_length=15)),
                ('compte_rendu_operatoire', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True, help_text="Renseigné si statut='complication' — description de l'incident.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chirurgien_principal', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.PROTECT, related_name='operations_dirigees', to='comptes.employe')),
                ('consultation_indication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_indiquees', to='consultations.consultation')),
                ('equipe', models.ManyToManyField(blank=True, help_text='Chirurgien(s) assistant(s), anesthésiste, infirmier(s) de bloc.', related_name='operations_assistees', to='comptes.employe')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='hospitalisations.hospitalisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='patients.patient')),
                ('service_chirurgie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='services.service')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='chirurgie.sallebloc')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date_heure_prevue'],
            },
        ),
    ]
