# Generated by Django 6.0.4 on 2026-07-19 00:38

import chirurgie.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirurgie', '0001_initial'),
        ('comptes', '0009 chef chirurgie role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='chirurgien_principal',
            field=models.ForeignKey(limit_choices_to=chirurgie.models._roles_actes_medicaux, on_delete=django.db.models.deletion.PROTECT, related_name='operations_dirigees', to='comptes.employe'),
        ),
    ]
