# Generated by Django 6.0 on 2026-07-23 22:44

import chirurgie.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirurgie', '0002_alter_operation_chirurgien_principal'),
        ('comptes', '0010_rappel'),
        ('consultations', '0008_rendezvous_type_evenement_and_more'),
        ('hospitalisations', '0001_initial'),
        ('patients', '0007_remove_patient_patient_nom_prenom_idx_and_more'),
        ('services', '0004_service_capacite_lits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='chirurgien_principal',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='consultation_indication',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='hospitalisation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='service_chirurgie',
        ),
        migrations.RemoveField(
            model_name='sallebloc',
            name='actif',
        ),
        migrations.AddField(
            model_name='sallebloc',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupée'), ('desinfection_approfondie', 'Désinfection approfondie'), ('maintenance', 'Maintenance')], default='disponible', max_length=25),
        ),
        migrations.CreateModel(
            name='InterventionChirurgicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(help_text='Ex. « Cure de hernie inguinale »', max_length=200)),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True)),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('deces_au_bloc', 'Décès au bloc'), ('annulee', 'Annulée')], default='programmee', max_length=15)),
                ('compte_rendu_operatoire', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True, help_text="Incident ou complication survenu pendant l'intervention, y compris en cas de décès au bloc.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chirurgien_principal', models.ForeignKey(limit_choices_to=chirurgie.models._roles_actes_medicaux, on_delete=django.db.models.deletion.PROTECT, related_name='operations_dirigees', to='comptes.employe')),
                ('consultation_indication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_indiquees', to='consultations.consultation')),
                ('equipe', models.ManyToManyField(blank=True, help_text='Chirurgien(s) assistant(s), anesthésiste, infirmier(s) de bloc — le rôle de chacun se lit sur son profil (spécialité).', related_name='operations_assistees', to='comptes.employe')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='hospitalisations.hospitalisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='patients.patient')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='chirurgie.sallebloc')),
                ('service_chirurgie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='services.service')),
            ],
            options={
                'verbose_name': 'Intervention chirurgicale',
                'verbose_name_plural': 'Interventions chirurgicales',
                'ordering': ['-heure_debut'],
            },
        ),
    ]
