# Generated by Django 6.0 on 2026-07-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirurgie', '0003_remove_operation_chirurgien_principal_and_more'),
        ('morgue', '0004_alter_deces_operation_liee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
