# Generated by Django 6.0.4 on 2026-06-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_employe_service_employe_employe_sexe_valid'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='chef_de_service',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to='comptes.employe'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
