# Generated by Django 6.0.4 on 2026-07-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_rendezvous_medecin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultation',
            name='consult_patient_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='rendezvous',
            name='rdv_patient_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='rendezvous',
            name='rdv_medecin_date_idx',
        ),
    ]
