# Generated by Django 6.0.4 on 2026-07-18 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_remove_consultation_consult_patient_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='consultation_liee',
            field=models.ForeignKey(blank=True, help_text="Consultation créée à partir de ce rendez-vous, une fois que le médecin l'a démarrée. Permet au planning de proposer 'Démarrer' ou 'Reprendre' la consultation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_origine', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Durée du rendez-vous en minutes, utilisée pour calculer l'heure de fin dans le planning (start/end du calendrier)."),
        ),
    ]