# Generated by Django 6.0.4 on 2026-07-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007 rdv duree et consultation liee '),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_evenement',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('intervention', 'Intervention'), ('reunion', 'Réunion'), ('garde', 'Garde'), ('visite_postoperatoire', 'Visite postopératoire'), ('autre', 'Autre')], default='consultation', help_text='Catégorie affichée dans le planning médecin (couleur/icône) — distincte de Consultation.type_evenement, propre au calendrier.', max_length=25),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='consultation_liee',
            field=models.ForeignKey(blank=True, help_text="Renseigné une fois qu'une Consultation a été créée depuis ce RDV (cf. mon_planning) — permet au frontend de proposer 'Reprendre' plutôt que 'Démarrer' la consultation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_origine', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Durée prévue en minutes — utilisée pour calculer end_time côté planning.'),
        ),
    ]
