# Generated by Django 6.0.4 on 2026-07-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_agent_admission_role'),
        ('consultations', '0008_rendezvous_type_evenement_and_more'),
        ('services', '0004_service_capacite_lits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='type_evenement',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('intervention', 'Intervention'), ('reunion', 'Réunion'), ('formation', 'Formation'), ('garde', 'Garde'), ('visite_postoperatoire', 'Visite postopératoire'), ('autre', 'Autre')], default='consultation', help_text='Catégorie affichée dans le planning médecin (couleur/icône) — distincte de Consultation.type_evenement, propre au calendrier.', max_length=25),
        ),
        migrations.CreateModel(
            name='EvenementAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_evenement', models.CharField(choices=[('reunion', 'Réunion'), ('formation', 'Formation'), ('garde', 'Garde'), ('autre', 'Autre')], default='reunion', max_length=20)),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='planifie', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to='comptes.employe')),
                ('participants', models.ManyToManyField(blank=True, help_text="Optionnel — si vide, l'événement est simplement visible par tout le service concerné.", related_name='evenements_administratifs', to='comptes.employe')),
                ('service', models.ForeignKey(blank=True, help_text="Service concerné. Laisser vide pour un événement transversal (tout l'hôpital) — dans ce cas, seul un superuser peut le modifier.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements_administratifs', to='services.service')),
            ],
            options={
                'verbose_name': 'Événement administratif',
                'verbose_name_plural': 'Événements administratifs',
                'ordering': ['-date_heure_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_heure_fin__gt', models.F('date_heure_debut'))), name='evenement_admin_fin_apres_debut')],
            },
        ),
    ]
