# Generated by Django 6.0.7 on 2026-09-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_consultation_decision_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage réel de la fin (passage à 'terminee'). Rempli automatiquement.", null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage réel du démarrage (passage à 'en_cours'). Rempli automatiquement.", null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='type_consultation',
            field=models.CharField(blank=True, choices=[('initiale', 'Consultation initiale'), ('suivi', 'Consultation de suivi'), ('controle', 'Consultation de contrôle'), ('urgence', "Consultation d'urgence"), ('preoperatoire', 'Consultation préopératoire'), ('postoperatoire', 'Consultation postopératoire'), ('teleconsultation', 'Téléconsultation'), ('autre', 'Autre')], default='', help_text="Type de consultation choisi dans la modale de démarrage (consultation initiale, suivi, contrôle...). Vide pour les consultations créées avant l'ajout de ce champ.", max_length=20),
        ),
    ]