# Generated by Django 6.0.4 on 2026-07-16 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedents', ' 0003_add_indexes'),
        ('patients', '0007_remove_patient_patient_nom_prenom_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='antecedent',
            name='antecedent_patient_statut_idx',
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents_details', to='patients.patient'),
        ),
    ]
