# Generated by Django 6.0.4 on 2026-06-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_consultation_type_evenement'),
        ('patients', '0003_remove_patient_photo_url_patient_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_antecedent', models.CharField(choices=[('maladie_chronique', 'Maladie chronique'), ('chirurgie', 'Chirurgie'), ('allergie', 'Allergie'), ('familial', 'Antécédent familial'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('libelle', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('resolu', 'Résolu')], default='actif', max_length=10)),
                ('date_diagnostic', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('consultation_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedents_crees', to='consultations.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents_detail', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Antécédent',
                'verbose_name_plural': 'Antécédents',
                'ordering': ['-date_diagnostic'],
                'constraints': [models.CheckConstraint(condition=models.Q(('type_antecedent__in', ['maladie_chronique', 'chirurgie', 'allergie', 'familial', 'autre'])), name='antecedent_type_valide'), models.CheckConstraint(condition=models.Q(('statut__in', ['actif', 'resolu'])), name='antecedent_statut_valide')],
            },
        ),
    ]
