# Generated by Django 6.0.7 on 2026-08-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_seed_medicaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeledocument',
            name='entete',
            field=models.TextField(blank=True, help_text='Texte affiché en haut du document. Jetons disponibles : {{patient.nom}}, {{patient.prenom}}, {{patient.age}}, {{patient.sexe}}, {{patient.numero_dossier}}, {{patient.date_naissance}}, {{consultation.motif}}, {{consultation.diagnostic}}, {{consultation.symptomes}}, {{consultation.ordonnance}}, {{consultation.date}}, {{medecin.nom}}, {{medecin.prenom}}, {{medecin.signature}}, {{service.nom}}, {{date_jour}}'),
        ),
        migrations.AlterField(
            model_name='modeledocument',
            name='pied_de_page',
            field=models.TextField(blank=True, help_text="Mentions légales / signature affichées en bas du document. Mêmes jetons que l'en-tête."),
        ),
    ]
