# Generated by Django 6.0.7 on 2026-07-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageurgence',
            name='date_prise_en_charge',
            field=models.DateTimeField(blank=True, help_text="Renseigné automatiquement dès qu'un médecin_examinateur est assigné — alimente le KPI 'temps moyen de prise en charge' (Analytics > Qualité).", null=True),
        ),
    ]