# Generated by Django 6.0.4 on 2026-04-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tension', 'Tension anormale'), ('glycemie', 'Glycémie anormale'), ('temperature', 'Température anormale'), ('frequence', 'Fréquence cardiaque anormale'), ('rdv', 'Rendez-vous manqué'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('non_lue', 'Non lue'), ('lue', 'Lue'), ('traitee', 'Traitée')], default='non_lue', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
