# Generated by Django 6.0.4 on 2026-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='employe',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
