# Generated by Django 6.0.4 on 2026-06-29 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_employe_photo_url_employe_photo_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'medecin', 'infirmier', 'secretaire', 'laborantin'])), name='employe_role_valid'),
        ),
    ]
