# Generated by Django 6.0.4 on 2026-06-29 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_add_role_check_constraint'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.CheckConstraint(condition=models.Q(('sexe__in', ['M', 'F'])), name='employe_sexe_valid'),
        ),
    ]
