# Generated by Django 6.0.4 on 2026-07-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_employe_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Préférences utilisateur stockées en JSON'),
        ),
        migrations.AddField(
            model_name='employe',
            name='signature_medicale',
            field=models.TextField(blank=True, help_text='Texte affiché en bas des ordonnances et comptes rendus'),
        ),
    ]
