# Generated by hand to match Django 6.0.4 migration format

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_employe_preferences_employe_signature_medicale'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='est_major',
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Infirmier(ère) major — responsable de l'organisation des soins "
                    "infirmiers de son service (assignation des patients, planning "
                    "et congés des infirmiers). Uniquement pertinent si role='infirmier'."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.CheckConstraint(
                condition=models.Q(('est_major', False)) | models.Q(('role', 'infirmier')),
                name='employe_est_major_seulement_infirmier',
            ),
        ),
    ]