# Generated by Django 6.0.4 on 2026-07-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007 employe est major'),
        ('services', '0003 chef de service allow laborantin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('est_chirurgicale', models.BooleanField(default=False, help_text="Coché si cette spécialité pratique des actes chirurgicaux (conditionne l'affichage dans les listes de chirurgiens).")),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='specialite_principale',
            field=models.ForeignKey(blank=True, help_text="Version structurée de `specialite` (texte libre, conservé pour compatibilité). À terme, migrer les valeurs de `specialite` vers ce champ puis déprécier l'ancien.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='comptes.specialite'),
        ),
        migrations.CreateModel(
            name='HabilitationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitations_services', to='comptes.employe')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirurgiens_habilites', to='services.service')),
            ],
            options={
                'verbose_name': 'Habilitation à opérer dans un service',
                'verbose_name_plural': 'Habilitations à opérer dans un service',
                'unique_together': {('employe', 'service')},
            },
        ),
    ]
