# Generated by hand to match Django 6.0.4 migration format

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_specialite_employe_specialite_principale_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employe',
            name='employe_role_valid',
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrateur'),
                    ('medecin', 'Médecin'),
                    ('infirmier', 'Infirmier(ère)'),
                    ('secretaire', 'Secrétaire'),
                    ('laborantin', 'Laborantin'),
                    ('chef_chirurgie', 'Chef de Chirurgie'),
                ],
                default='infirmier',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.CheckConstraint(
                condition=models.Q(('role__in', [
                    'admin', 'medecin', 'infirmier', 'secretaire',
                    'laborantin', 'chef_chirurgie',
                ])),
                name='employe_role_valid',
            ),
        ),
    ]