# Generated by Django 6.0 on 2026-07-22 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009 chef chirurgie role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('fait', models.BooleanField(default=False)),
                ('date_echeance', models.DateField(blank=True, help_text='Optionnel — date à laquelle le rappel doit être traité.', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='comptes.employe')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['fait', 'date_echeance', '-date_creation'],
            },
        ),
    ]
