# Generated by Django 6.0.4 on 2026-07-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_agent_admission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='specialite_principale',
            field=models.CharField(blank=True, choices=[('cardiologie_generale', 'Cardiologie générale'), ('cardiologie_interventionnelle', 'Cardiologie interventionnelle'), ('rythmologie', 'Rythmologie'), ('medecine_interne', 'Médecine interne'), ('maladies_infectieuses', 'Maladies infectieuses'), ('pediatrie_generale', 'Pédiatrie générale'), ('neonatologie', 'Néonatologie'), ('diabetologie', 'Diabétologie'), ('endocrinologie', 'Endocrinologie'), ('medecine_urgence', "Médecine d'urgence"), ('reanimation_polyvalente', 'Réanimation polyvalente'), ('chirurgie_digestive', 'Chirurgie digestive'), ('chirurgie_orthopedique', 'Chirurgie orthopédique'), ('chirurgie_vasculaire', 'Chirurgie vasculaire'), ('chirurgie_thoracique', 'Chirurgie thoracique'), ('chirurgie_cardiaque', 'Chirurgie cardiaque'), ('gynecologie_obstetrique', 'Gynécologie-Obstétrique'), ('neurologie_generale', 'Neurologie générale'), ('neurologie_vasculaire', 'Neurologie vasculaire'), ('pneumologie_generale', 'Pneumologie générale'), ('pneumologie_infectiologie', 'Pneumologie-Infectiologie'), ('nephrologie', 'Néphrologie'), ('dialyse_peritoneale', 'Dialyse péritonéale'), ('orl_chirurgie_cervico_faciale', 'ORL-Chirurgie cervico-faciale'), ('ophtalmologie', 'Ophtalmologie'), ('biologie_medicale', 'Biologie médicale'), ('anesthesie_reanimation', 'Anesthésie-Réanimation')], default='', help_text="Version structurée de `specialite` (texte libre, conservé pour compatibilité). À terme, migrer les valeurs de `specialite` vers ce champ puis déprécier l'ancien.", max_length=40),
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
    ]
