# Generated by Django 6.0.7 on 2026-08-01 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0012_alter_employe_specialite_principale_and_more'),
        ('services', '0005_creer_services_urgences_triage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employe',
            name='employe_role_valid',
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier(ère)'), ('secretaire', 'Secrétaire'), ('laborantin', 'Laborantin'), ('chef_chirurgie', 'Chef de Chirurgie'), ('agent_admission', "Agent d'Admission"), ('facturier', 'Facturier(ère)'), ('caissier', 'Caissier(ère)')], default='infirmier', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'medecin', 'infirmier', 'secretaire', 'laborantin', 'chef_chirurgie', 'agent_admission', 'facturier', 'caissier'])), name='employe_role_valid'),
        ),
    ]