# Generated by Django 6.0.7 on 2026-09-02 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0013_remove_employe_employe_role_valid_alter_employe_role_and_more'),
        ('consultations', '0010_consultation_decision_orientation'),
        ('patients', '0011_alter_patient_statut_orientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerniereActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, choices=[('dossier', 'Dossier médical'), ('consultation', 'Consultation'), ('prescription', 'Prescription'), ('document', 'Document'), ('hospitalisation', 'Hospitalisation'), ('signes_vitaux', 'Signes vitaux')], max_length=20)),
                ('date_activite', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='consultations.consultation')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derniere_activite', to='comptes.employe')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dernière activité',
                'verbose_name_plural': 'Dernières activités',
            },
        ),
    ]