# Generated by Django 6.0.4 on 2026-07-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0006_employe_preferences_employe_signature_medicale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type', models.CharField(choices=[('presentiel', 'Présentiel'), ('garde', 'Garde'), ('astreinte', 'Astreinte'), ('teleconsultation', 'Téléconsultation')], default='presentiel', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='comptes.employe')),
            ],
            options={
                'verbose_name': 'Créneau de disponibilité',
                'ordering': ['jour', 'heure_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='creneau_heure_fin_apres_debut')],
            },
        ),
        migrations.CreateModel(
            name='ExceptionDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conge', 'Congé'), ('absence', 'Absence'), ('garde', 'Garde exceptionnelle'), ('formation', 'Formation'), ('mission', 'Mission extérieure')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('valide', models.BooleanField(default=False, help_text="Validé par l'admin ou chef de service")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='comptes.employe')),
            ],
            options={
                'verbose_name': 'Exception de disponibilité',
                'ordering': ['-date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='exception_date_fin_apres_debut')],
            },
        ),
    ]
