# Generated by hand to match Django 6.0.4 migration format

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0002_exception_statut'),
        ('comptes', '0006_employe_preferences_employe_signature_medicale'),
        ('patients', '0006_add_indexes'),
        ('services', '0002_add_date_modification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignationPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('matin', 'Matin (7h–15h)'), ('apres_midi', 'Après-midi (15h–23h)'), ('nuit', 'Nuit (23h–7h)')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infirmier', models.ForeignKey(limit_choices_to={'role': 'infirmier'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients_assignes', to='comptes.employe')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infirmiers_assignes', to='patients.patient')),
                ('service', models.ForeignKey(help_text="Dénormalisé depuis l'infirmier au moment de la création — évite une jointure pour le scoping.", on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='services.service')),
            ],
            options={
                'verbose_name': 'Assignation infirmier ↔ patient',
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignationpatient',
            constraint=models.UniqueConstraint(fields=('infirmier', 'patient', 'date', 'shift'), name='assignation_unique_infirmier_patient_date_shift'),
        ),
    ]