# Generated by Django 6.0.4 on 2026-07-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signes_vitaux', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='signesvitaux',
            name='signes_patient_date_idx',
        ),
    ]
