# Generated by Django 6.0.7 on 2026-08-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0003_remove_demandeanalyse_analyse_patient_statut_idx_and_more'),
        ('comptes', '0013_remove_employe_employe_role_valid_alter_employe_role_and_more'),
        ('consultations', '0009_alter_rendezvous_type_evenement_and_more'),
        ('hospitalisations', '0001_initial'),
        ('patients', '0010_alter_patient_statut_orientation'),
        ('services', '0005_creer_services_urgences_triage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancierPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total_echeancier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_echeances', models.PositiveIntegerField()),
                ('periodicite', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('bimensuelle', 'Bimensuelle')], max_length=15)),
                ('date_premiere_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('solde', 'Soldé'), ('en_defaut', 'En défaut'), ('annule', 'Annulé')], default='actif', max_length=15)),
                ('engagement_signe', models.BooleanField(default=False)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('document_signe_url', models.CharField(blank=True, max_length=255)),
                ('garant_nom', models.CharField(blank=True, max_length=150)),
                ('garant_telephone', models.CharField(blank=True, max_length=20)),
                ('garant_cni', models.CharField(blank=True, max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeanciers_crees', to='comptes.employe')),
            ],
            options={
                'verbose_name': 'Échéancier de paiement',
                'verbose_name_plural': 'Échéanciers de paiement',
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.PositiveIntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('impayee', 'Impayée')], default='a_venir', max_length=15)),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='facturation.echeancierpaiement')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['numero_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouverte', 'Ouverte (séjour en cours)'), ('en_attente', 'En attente de paiement'), ('payee_partiellement', 'Payée partiellement'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('mutuelle_nom', models.CharField(blank=True, max_length=150)),
                ('numero_mutuelle', models.CharField(blank=True, max_length=50)),
                ('part_assurance_pourcentage_defaut', models.DecimalField(decimal_places=2, default=0, help_text='Taux appliqué par défaut aux lignes sans taux propre (LigneFacture.taux_prise_en_charge_assurance) — 0 si patient non couvert. Le taux réel appliqué varie PAR LIGNE (ex: 80% consultation, 50% pharmacie).', max_digits=5)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_part_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_part_patient', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to='comptes.employe')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='hospitalisations.hospitalisation')),
                ('patient', models.ForeignKey(help_text="PROTECT plutôt que CASCADE : on ne supprime jamais une facture par ricochet en supprimant un patient — c'est une pièce comptable, pas un simple historique médical.", on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='patients.patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='services.service')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AddField(
            model_name='echeancierpaiement',
            name='facture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='echeancier', to='facturation.facture'),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('consultation', 'Consultation'), ('hospitalisation', 'Hospitalisation (nuitée)'), ('examen_laboratoire', 'Examen de laboratoire'), ('acte_chirurgical', 'Acte chirurgical'), ('medicament', 'Médicament / Pharmacie'), ('autre', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('code_acte', models.CharField(blank=True, max_length=30)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_prise_en_charge_assurance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('montant_part_assurance_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_part_patient_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut_assurance', models.CharField(choices=[('non_soumis', 'Non soumis'), ('soumis', "Soumis à l'assurance"), ('valide', "Validé par l'assurance"), ('rejete_partiel', 'Rejeté partiellement'), ('rejete', 'Rejeté')], default='non_soumis', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission_assurance', models.DateTimeField(blank=True, null=True)),
                ('date_reponse_assurance', models.DateTimeField(blank=True, null=True)),
                ('date_acte', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='consultations.consultation')),
                ('demande_analyse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='analyses.demandeanalyse')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='hospitalisations.hospitalisation')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['date_acte'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('carte_bancaire', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('prise_en_charge_assurance', 'Prise en charge assurance')], max_length=30)),
                ('operateur_mobile_money', models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('autre', 'Autre')], max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('echeance', models.ForeignKey(blank=True, help_text="Renseigné si ce paiement règle une échéance précise d'un EcheancierPaiement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='facturation.echeance')),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaisses', to='comptes.employe')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddConstraint(
            model_name='echeance',
            constraint=models.UniqueConstraint(fields=('echeancier', 'numero_echeance'), name='echeance_numero_unique_par_echeancier'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('part_assurance_pourcentage_defaut__gte', 0), ('part_assurance_pourcentage_defaut__lte', 100)), name='facture_taux_assurance_defaut_valide'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='ligne_facture_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_prise_en_charge_assurance__isnull', True), models.Q(('taux_prise_en_charge_assurance__gte', 0), ('taux_prise_en_charge_assurance__lte', 100)), _connector='OR'), name='ligne_facture_taux_valide'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='paiement_montant_positif'),
        ),
    ]