# Generated by Django 6.0.7 on 2026-08-04 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('services', '0005_creer_services_urgences_triage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('consultation', 'Consultation'), ('hospitalisation', 'Hospitalisation (nuitée)'), ('examen_laboratoire', 'Examen de laboratoire'), ('acte_chirurgical', 'Acte chirurgical'), ('medicament', 'Médicament / Pharmacie'), ('autre', 'Autre')], max_length=20)),
                ('code_acte', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True, help_text='Un tarif désactivé disparaît du sélecteur de nouvelle ligne, mais reste consultable pour les factures déjà émises qui le référencent (jamais supprimé physiquement).')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifs_actes', to='services.service')),
            ],
            options={
                'verbose_name': "Tarif d'acte",
                'verbose_name_plural': "Tarifs d'actes",
                'ordering': ['type_acte', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='tarif_acte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='facturation.tarifacte'),
        ),
        migrations.AddConstraint(
            model_name='tarifacte',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire__gte', 0)), name='tarif_acte_prix_positif'),
        ),
    ]