# Generated by Django 6.0.4 on 2026-06-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_photo_url_patient_photo_path'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('groupe_sanguin__in', ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']), ('groupe_sanguin', ''), _connector='OR'), name='patient_groupe_sanguin_valid'),
        ),
    ]
