# Generated by Django 6.0.4 on 2026-06-29 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_employe_service_employe_employe_sexe_valid'),
        ('patients', '0004_add_groupe_sanguin_check_constraint'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medecin_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='comptes.employe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('sexe__in', ['M', 'F'])), name='employe_sexe_validate'),
        ),
    ]
