# Generated by Django 6.0.4 on 2026-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_nom_prenom_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_actif_idx',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_naissance_estimee',
            field=models.BooleanField(default=False, help_text="La date de naissance n'est pas connue avec certitude : elle a été déduite d'un âge approximatif déclaré (convention : 1er juillet de l'année de naissance estimée). À corriger dès que la vraie date est connue."),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut_vital',
            field=models.CharField(choices=[('vivant', 'Vivant'), ('decede', 'Décédé')], default='vivant', help_text="Distinct de 'actif' : un patient décédé n'est pas 'inactif au sens dossier plus suivi', c'est un fait clinique définitif. Positionné automatiquement à 'décédé' par l'app morgue lors de l'enregistrement d'un décès.", max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='actif',
            field=models.BooleanField(default=True, help_text="Reflète une activité récente dans le dossier (consultation, hospitalisation, rendez-vous, signes vitaux). Recalculé périodiquement via 'python manage.py recalculer_patients_actifs' (seuil par défaut : 3 ans) ; peut aussi être ajusté manuellement."),
        ),
    ]
