# Generated by Django 6.0.4 on 2026-07-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_agent_admission_role'),
        ('patients', '0007_remove_patient_patient_nom_prenom_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_lien',
            field=models.CharField(blank=True, help_text='Lien de parenté avec le patient (ex : conjoint, parent, ami).', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='mutuelle',
            field=models.CharField(blank=True, help_text='Nom de la mutuelle / assurance santé (vide = non couvert ou inconnu).', max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_mutuelle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut_orientation',
            field=models.CharField(choices=[('en_attente_orientation', "En attente d'orientation"), ('oriente', 'Orienté'), ('en_consultation', 'En consultation'), ('hospitalise', 'Hospitalisé'), ('sorti', 'Sorti')], default='en_attente_orientation', help_text="Parcours administratif du patient depuis son admission. Un patient créé par le Service des Admissions démarre à 'en_attente_orientation' (pas encore de service) puis passe à 'oriente' une fois affecté à un service via l'action PATCH /patients/{id}/orienter/. Un patient créé directement par un service (secrétaire/médecin, hors admissions) est considéré 'oriente' d'emblée puisqu'il a déjà un service.", max_length=25),
        ),
        migrations.CreateModel(
            name='Accompagnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lien_parente', models.CharField(blank=True, help_text='Lien avec le patient (ex : conjoint, parent, enfant, ami).', max_length=50)),
                ('cni', models.CharField(blank=True, help_text="Numéro de pièce d'identité présentée (CNI, passeport…) — utilisé pour la recherche inversée et le contrôle d'accès.", max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('sorti', 'Sorti')], default='present', help_text="PRÉSENT tant que l'accompagnant n'a pas été pointé en sortie (contrôle d'accès) ; SORTI une fois son passage terminé.", max_length=10)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('enregistre_par', models.ForeignKey(blank=True, help_text="Agent ayant enregistré l'accompagnant (traçabilité).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompagnants_enregistres', to='comptes.employe')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompagnants', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Accompagnant',
                'verbose_name_plural': 'Accompagnants',
                'ordering': ['-date_entree'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='accompagnant_nom_prenom_idx'), models.Index(fields=['telephone'], name='accompagnant_telephone_idx'), models.Index(fields=['cni'], name='accompagnant_cni_idx'), models.Index(fields=['statut'], name='accompagnant_statut_idx')],
            },
        ),
    ]
