# Generated by Django 6.0.4 on 2026-07-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_workflow_admission_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='statut_orientation',
            field=models.CharField(choices=[('en_attente_validation_service', 'En attente de validation par le service'), ('admis_dans_le_service', 'Admis dans le service'), ('en_consultation', 'En consultation'), ('hospitalise', 'Hospitalisé'), ('admis_urgences', 'Admis aux urgences'), ('sorti', 'Sorti')], default='en_attente_validation_service', help_text="Parcours administratif du patient depuis son admission : 'en_attente_validation_service' (créé + orienté par les Admissions, en attente que le secrétariat du service confirme l'arrivée) → 'admis_dans_le_service' (confirmé) → 'en_consultation' / 'hospitalise' (mis à jour AUTOMATIQUEMENT par les apps consultations/hospitalisations à la création d'un enregistrement, voir leurs save()) → 'sorti'. Chemin parallèle : 'admis_urgences' pour une admission d'urgence vitale à identité provisoire (voir identite_provisoire), avant régularisation.", max_length=30),
        ),
    ]
